=== Cybereason-Public/owLSM/src/Userspace/configuration/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "OWLSM Configuration Schema",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "features": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "file_monitoring": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        },
                        "events": {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                                "chmod": {
                                    "type": "boolean"
                                },
                                "chown": {
                                    "type": "boolean"
                                },
                                "file_create": {
                                    "type": "boolean"
                                },
                                "unlink": {
                                    "type": "boolean"
                                },
                                "rename": {
                                    "type": "boolean"
                                },
                                "write": {
                                    "type": "boolean"
                                },
                                "read": {
                                    "type": "boolean"
                                },
                                "mkdir": {
                                    "type": "boolean"
                                },
                                "rmdir": {
                                    "type": "boolean"
                                }
                            }
                        }
                    }
                },
                "network_monitoring": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        }
                    }
                },
                "shell_commands_monitoring": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "userspace": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "max_events_queue_size": {
                    "type": "integer",
                    "minimum": 1
                },
                "output_type": {
                    "$ref": "#/definitions/OUTPUT_TYPE"
                },
                "log_level": {
                    "$ref": "#/definitions/LOG_LEVEL"
                },
                "set_limits": {
                    "type": "boolean"
                },
                "log_location": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "kernel": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "log_level": {
                    "$ref": "#/definitions/LOG_LEVEL"
                }
            }
        },
        "rules": {
            "type": "object",
            "additionalProperties": false,
            "required": ["id_to_string", "id_to_predicate", "id_to_ip", "rules"],
            "properties": {
                "id_to_string": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/rule_string_t"
                    }
                },
                "id_to_predicate": {
                    "type": "object",
                    "minProperties": 1,
                    "additionalProperties": {
                        "$ref": "#/definitions/predicate_t"
                    }
                },
                "id_to_ip": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/rule_ip_t"
                    }
                },
                "rules": {
                    "type": "array",
                    "minItems": 0,
                    "items": {
                        "$ref": "#/definitions/rule_t"
                    }
                }
            }
        }
    },
    "definitions": {
        "rule_string_t": {
            "type": "object",
            "required": ["value", "string_type"],
            "additionalProperties": false,
            "properties": {
                "value": {
                    "type": "string",
                    "maxLength": 32
                },
                "string_type": {
                    "type": "integer",
                    "enum": [0, 1, 2]
                }
            }
        },
        "rule_ip_t": {
            "type": "object",
            "required": ["ip", "cidr", "ip_type"],
            "additionalProperties": false,
            "properties": {
                "ip": {
                    "type": "string"
                },
                "cidr": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 128
                },
                "ip_type": {
                    "type": "integer",
                    "enum": [2, 10]
                }
            }
        },
        "predicate_t": {
            "type": "object",
            "required": ["field", "comparison_type", "string_idx", "numerical_value", "fieldref"],
            "additionalProperties": false,
            "properties": {
                "field": {
                    "type": "string"
                },
                "comparison_type": {
                    "type": "string",
                    "enum": [
                        "exactmatch",
                        "contains",
                        "startswith",
                        "endswith",
                        "equal",
                        "above",
                        "below",
                        "equal_above",
                        "equal_below",
                        "regex"
                    ]
                },
                "string_idx": {
                    "type": "integer",
                    "minimum": -1
                },
                "numerical_value": {
                    "type": "integer",
                    "minimum": -1
                },
                "fieldref": {
                    "type": "string"
                }
            },
            "oneOf": [
                {
                    "properties": {
                        "string_idx": {
                            "const": -1
                        },
                        "numerical_value": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "fieldref": {
                            "const": "FIELD_TYPE_NONE"
                        }
                    }
                },
                {
                    "properties": {
                        "string_idx": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "numerical_value": {
                            "const": -1
                        },
                        "fieldref": {
                            "const": "FIELD_TYPE_NONE"
                        }
                    }
                },
                {
                    "properties": {
                        "string_idx": {
                            "const": -1
                        },
                        "numerical_value": {
                            "const": -1
                        },
                        "fieldref": {
                            "type": "string",
                            "not": { "const": "FIELD_TYPE_NONE" }
                        }
                    }
                }
            ]
        },
        "token_t": {
            "type": "object",
            "required": ["operator_type"],
            "additionalProperties": false,
            "properties": {
                "operator_type": {
                    "type": "string",
                    "enum": [
                        "OPERATOR_PREDICATE",
                        "OPERATOR_AND",
                        "OPERATOR_OR",
                        "OPERATOR_NOT"
                    ]
                },
                "predicate_idx": {
                    "type": "integer",
                    "minimum": 0
                }
            },
            "if": {
                "properties": {
                    "operator_type": { "const": "OPERATOR_PREDICATE" }
                }
            },
            "then": {
                "required": ["predicate_idx"]
            }
        },
        "rule_metadata_t": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "severity": {
                    "type": "string",
                    "enum": [
                        "unknown",
                        "informational",
                        "low",
                        "medium",
                        "high",
                        "critical"
                    ]
                },
                "mitre_tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                }
            }
        },
        "rule_t": {
            "type": "object",
            "required": ["id", "action", "applied_events", "tokens"],
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer",
                    "minimum": 1
                },
                "metadata": {
                    "$ref": "#/definitions/rule_metadata_t"
                },
                "description": {
                    "type": "string"
                },
                "action": {
                    "type": "string",
                    "enum": [
                        "ALLOW_EVENT",
                        "BLOCK_EVENT",
                        "BLOCK_KILL_PROCESS",
                        "BLOCK_KILL_PROCESS_KILL_PARENT",
                        "KILL_PROCESS",
                        "EXCLUDE_EVENT"
                    ]
                },
                "min_version": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
                },
                "max_version": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
                },
                "applied_events": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string",
                        "enum": [
                            "EXEC",
                            "FORK",
                            "EXIT",
                            "FILE_CREATE",
                            "CHOWN",
                            "CHMOD",
                            "WRITE",
                            "READ",
                            "UNLINK",
                            "RENAME",
                            "NETWORK",
                            "MKDIR",
                            "RMDIR"
                        ]
                    }
                },
                "tokens": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/token_t"
                    }
                }
            }
        },
        "LOG_LEVEL": {
            "type": "string",
            "enum": [
                "LOG_LEVEL_DEBUG",
                "LOG_LEVEL_INFO",
                "LOG_LEVEL_WARNING",
                "LOG_LEVEL_ERROR"
            ]
        },
        "OUTPUT_TYPE": {
            "type": "string",
            "enum": [
                "JSON",
                "PROTOBUF",
                "FLATBUFFERS"
            ]
        }
    }
}

=== Cybereason-Public/owLSM/src/Tests/Automation/resources/flatbuffers_config.json
{
  "features": {
    "file_monitoring": {
      "enabled": true,
      "events": {
        "chmod": true,
        "chown": true,
        "file_create": true,
        "unlink": true,
        "rename": true,
        "write": true,
        "read": true,
        "mkdir": true,
        "rmdir": true
      }
    },
    "network_monitoring": {
      "enabled": true
    },
    "shell_commands_monitoring": {
      "enabled": true
    }
  },
  "userspace": {
    "max_events_queue_size": 10000,
    "output_type": "FLATBUFFERS",
    "log_level": "LOG_LEVEL_INFO",
    "set_limits": true
  },
  "kernel": {
    "log_level": "LOG_LEVEL_WARNING"
  },
  "rules": {
    "id_to_string": {
      "0": {
        "value": "bin/chmod",
        "string_type": 0
      },
      "1": {
        "value": "666",
        "string_type": 1
      },
      "2": {
        "value": "test2",
        "string_type": 0
      }
    },
    "id_to_predicate": {
      "0": {
        "field": "process.pid",
        "comparison_type": "above",
        "string_idx": -1,
        "numerical_value": 100,
        "fieldref": "FIELD_TYPE_NONE"
      },
      "1": {
        "field": "process.euid",
        "comparison_type": "below",
        "string_idx": -1,
        "numerical_value": 5000,
        "fieldref": "FIELD_TYPE_NONE"
      },
      "2": {
        "field": "process.file.path",
        "comparison_type": "endswith",
        "string_idx": 0,
        "numerical_value": -1,
        "fieldref": "FIELD_TYPE_NONE"
      },
      "3": {
        "field": "process.cmd",
        "comparison_type": "contains",
        "string_idx": 1,
        "numerical_value": -1,
        "fieldref": "FIELD_TYPE_NONE"
      },
      "4": {
        "field": "target.file.path",
        "comparison_type": "endswith",
        "string_idx": 2,
        "numerical_value": -1,
        "fieldref": "FIELD_TYPE_NONE"
      },
      "5": {
        "field": "chmod.requested_mode",
        "comparison_type": "equal",
        "string_idx": -1,
        "numerical_value": 438,
        "fieldref": "FIELD_TYPE_NONE"
      }
    },
    "id_to_ip": {},
    "rules": [
      {
        "id": 4,
        "metadata": {
          "description": "Test rule 4 - CHMOD block with process euid below threshold",
          "title": "",
          "severity": "unknown",
          "mitre_tags": [],
          "name": "",
          "author": ""
        },
        "action": "BLOCK_EVENT",
        "applied_events": [
          "CHMOD"
        ],
        "tokens": [
          {
            "operator_type": "OPERATOR_PREDICATE",
            "predicate_idx": 0
          },
          {
            "operator_type": "OPERATOR_PREDICATE",
            "predicate_idx": 1
          },
          {
            "operator_type": "OPERATOR_PREDICATE",
            "predicate_idx": 2
          },
          {
            "operator_type": "OPERATOR_PREDICATE",
            "predicate_idx": 3
          },
          {
            "operator_type": "OPERATOR_PREDICATE",
            "predicate_idx": 4
          },
          {
            "operator_type": "OPERATOR_PREDICATE",
            "predicate_idx": 5
          },
          {
            "operator_type": "OPERATOR_AND"
          },
          {
            "operator_type": "OPERATOR_AND"
          },
          {
            "operator_type": "OPERATOR_AND"
          },
          {
            "operator_type": "OPERATOR_AND"
          },
          {
            "operator_type": "OPERATOR_AND"
          }
        ],
        "min_version": "0.0.1",
        "max_version": "1000.0.22"
      }
    ]
  }
}
